name: Install Apache HTTPD

on:
  workflow_dispatch:

jobs:
  setup_httpd:
    runs-on: self-hosted  # assumes this is a CentOS 9 runner
    steps:
      - name: Install Apache
        run: |
          sudo dnf install -y httpd
          sudo systemctl enable --now httpd
          sudo firewall-cmd --permanent --add-service=http || true
          sudo firewall-cmd --permanent --add-service=https || true
          sudo firewall-cmd --reload || true
          sudo echo "Hello" > /var/www/html/index.html
          sudo systemctl status httpd
